### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ArturWroblewski**
Added a YouTube video link showing the minigalaxy.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Sorry for waiting so long with replying to this one. I think it would be cool to include the video, but I don't like just having it as a link. Do you know if it is possible to show the youtube web player inside the README and on the website?

**Comment by ArturWroblewski** [comment]
I have to prepare the animated gif manually. You can't convert from video so it will take some time.

**Comment by sharkwouter** [comment]
That's a shame, I was not aware of that. Then maybe a short gif might be better.

Let me come back to you on this after the release. I think this is not required to be ready before then. Feel free to join our [Discord](https://discord.gg/RC4cXVD) if you'd like to have a chat about it.

**Comment by sharkwouter** [comment]
I've thought about this for a while longer. In the end, I don't really think a video or gif adds much to the existing screenshot.

Sorry for taking so long for this conclusion. So much has happened since February. That's not a good excuse, though, I shouldn't have let you wait :(

**Pull request closed without merging**
