### PR TITLE
Change two dots to ellipsis

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by sharkwouter** [comment]
Thanks for the PR. I was a bit sceptical, but now I've tried it I think this does look better than before. The only issue is that it has to be consistent with all the translations as well. If you wouldn't mind updating the translations in data/po as well, I would like to merge it, otherwise I'm afraid I'd rather leave it out. Let me know what you decide.

**Comment by TotalCaesar659** [comment]
@sharkwouter I've fixed translations, how to resolve these conflicts?

**Comment by sharkwouter** [comment]
I'll look into this tomorrow. Thanks!

**Comment by sharkwouter** [comment]
Thanks! I've merged this now!

**Pull request merged**
