### PR TITLE
Fix_210

### PR DESCRIPTION
**Pull request by makson96**
Personally I was not affected by #210 ,but I noticed that __check_for_update_dlc() was not really called in separate thread.
Could you check if this simple fix can sole this issue?

### CODE REVIEW

**Comment by sharkwouter** [comment]
Good catch

**Review by sharkwouter — APPROVED** [review]

**Review by sharkwouter — CHANGES_REQUESTED** [review]
I was a little bit too quick with approving and found 2 potential issues. There are 2 lines in the function being called which can cause a segmentation fault, since you cannot modify Gtk widgets in a separate thread. To get around this you can make the main thread execute the modification when it has time using the ``GLib.idle_add`` function. 

I see the issue in the following lines:

- https://github.com/sharkwouter/minigalaxy/blob/a15165a0cf273cae1417ff435722b49ca2b5e55c/minigalaxy/ui/gametile.py#L323
- https://github.com/sharkwouter/minigalaxy/blob/a15165a0cf273cae1417ff435722b49ca2b5e55c/minigalaxy/ui/gametile.py#L320

**Comment by makson96** [comment]
Hi,
Thank you for the review. I have addressed this issue.
I also added:
"GLib.idle_add" to some calls in __check_for_dlc() as it is called inside of __check_for_update_dlc()
Could you please review it again.

**Comment by sharkwouter** [comment]
That works, thanks!

**Pull request merged**
