### PR TITLE
Remove old general FPS value

### PR DESCRIPTION
**Pull request by TotalCaesar659**
It was a leftover after changing to game-related ones.

### CODE REVIEW

**Comment by Odelpasso** [comment]
Why do you want delete this option ?
Show_FPS is still used, the option has been moved to Properties from Preference window.

**Comment by TotalCaesar659** [comment]
It's used? Well, FPS value now stores in separate minigalaxy-info.json for the game, but ""show_fps": False" is also saved in main minigalaxy.json. So I thought it's doesn't needed (because it can't be changed in main preferences now), tested and haven't found any bugs.
OK I can close this PR if you want.

**Comment by sharkwouter** [comment]
> Why do you want delete this option ?
> Show_FPS is still used, the option has been moved to Properties from Preference window.

This is a bit strange. Maybe we could change this, since it's now per game it's a bit odd to still need to global configuration value.

**Comment by TotalCaesar659** [comment]
@sharkwouter I'm little bit confused too. If you want to change it, tell me and I'll re-open it.

**Pull request closed without merging**
