### PR TITLE
Use DLC icon cache

### PR DESCRIPTION
**Pull request by TotalCaesar659**
This PR uses cache for DLC icons for saving some traffic and requests to GOG.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Can you make a screenshot of how this should look? Because I'm a bit confused

**Comment by TotalCaesar659** [comment]
Here is Frostpunk DLC list:

If you change icon files in cache, it will be read correctly:

This cache also may be used for base game icons in the future.

**Comment by sharkwouter** [comment]
@TotalCaesar659 I would like to merge this, but there is a merge conflict at the moment. Could you look into that?

**Comment by TotalCaesar659** [comment]
Finally found some time to do this. Rebased, looks like there is no more warnings and it can be merged.
P.S. @sharkwouter Thank you very much for making me contributor, I'll try to make Minigalaxy better as I possibly can (and not to riun it) :-)

**Review by sharkwouter — APPROVED** [review]

**Comment by sharkwouter** [comment]
Thank you for your contributions, it's really appreciated even if I don't always have time to review in a timely manner. I'm sorry for that. It's great to have more good contributors on this project.

**Pull request merged**
