### PR TITLE
Add Fedora installation instructions

### PR DESCRIPTION
**Pull request by tim77**

### CODE REVIEW

**Comment by sharkwouter** [comment]
Thanks! It works well, I'll merge it.

**Comment by tim77** [comment]
Soon i'll push it in official repos. Thank you!

**Comment by sharkwouter** [comment]
I'm currently releasing version 0.9.1 fixing some annoying crashes. Hopefully you can easily update the package in the coming days.

**Comment by tim77** [comment]
✅ 0.9.1 https://copr.fedorainfracloud.org/coprs/atim/minigalaxy/build/1135759/

**Comment by sharkwouter** [comment]
Awesome, thanks! I'll update the release announcement

**Pull request merged**
