### PR TITLE
Add zh_TW translations.

### PR DESCRIPTION
**Pull request by s8321414**
I added zh_TW translations, please review and merge it :smiley:

### CODE REVIEW

**Comment by sharkwouter** [comment]
Oh wow, thanks! That's unexprected. I'll try to review it as best I can, but at the end of the day I don't know Taiwanese, so I hope it's allright 😅

**Comment by sharkwouter** [comment]
Okay, I've reviewed it with the help of Google Translate and tested it. There is one change I will ask for. Could you rename the file to ``zh_TW.po``? Then the compile script will generate directory which minigalaxy can find.

**Comment by sharkwouter** [comment]
Thanks a lot! I'll implement it and give you attribution tomorrow :)

**Comment by sharkwouter** [comment]
How would I call this in the changelog? Taiwanese? Traditional Chinese? Taiwan Chinese?

**Comment by s8321414** [comment]
You can use either Traditional Chinese, Chinese (Taiwan) or Taiwanese Mandarin :smiley: 
I may prefer last one :smiley:

**Pull request merged**
