### PR TITLE
Added Spanish from Spain translation

### PR DESCRIPTION
**Pull request by mbarrio**
Basically the existing es.po Spanish translation with some verb tenses and terms changed to better suit the Spanish spoken in Spain. I have also corrected and completed some strings.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Thanks for the PR. This seems to be good work. I'm a little bit conflicted about the "Spanish from Spain" here as I would expect Spanish to be that unless otherwise specified. Do you know where the Spanish in the other file is from?

**Comment by sharkwouter** [comment]
That is totally fair. Thanks for the information!

Could you make one small change? I think it would look nicer if the locale was called ``Spanish (Spain)`` in ``constants.py`` instead of ``Spanish from Spain``.

**Comment by mbarrio** [comment]
> That is totally fair. Thanks for the information!
> 
> Could you make one small change? I think it would look nicer if the locale was called `Spanish (Spain)` in `constants.py` instead of `Spanish from Spain`.

Done ;-)

**Comment by sharkwouter** [comment]
Thanks a lot!

**Pull request merged**
