### PR TITLE
Adding the first version of the translation into Polish.

### PR DESCRIPTION
**Pull request by ArturWroblewski**
Polski	pl
Alternative name of the translation file pl_PL.po

### CODE REVIEW

**Comment by sharkwouter** [comment]
Thanks for the pull request. Sorry it is taking a while for me to get to reviewing it. I'll make sure to do so on the weekend. The last couple of days have been a bit busy for me

**Comment by sharkwouter** [comment]
I just tested it and it works well. Thanks for contributing!

**Comment by sharkwouter** [comment]
I'm planning on releasing a new version of Minigalaxy next Tuesday evening. Would it be possible for you to update the Polish translation? Thanks!

**Comment by ArturWroblewski** [comment]
> I'm planning on releasing a new version of Minigalaxy next Tuesday evening. Would it be possible for you to update the Polish translation? Thanks!

Of course. I'd be happy to assist. The new translation will be ready in time.

**Comment by sharkwouter** [comment]
Awesome! Thanks!

**Pull request merged**
