### PR TITLE
Add dark theme support

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by makson96** [comment]
I thought that Minigalaxy uses general system theme. So if somebody has dark mode in desktop, he/she will get dark Minigalaxy:
dark

**Comment by TotalCaesar659** [comment]
I know, but sometimes it's good to set dark theme just for Minigalaxy, e.g. for late gaming (https://www.gog.com/wishlist/galaxy/dark_theme). Besides, many other programs have this feature (Lutris, Bottles, Bleachbit etc.)
Of course, you can close it if you want, but it should be good to take more opinions.

**Comment by makson96** [comment]
Thanks for the clarification.

**Comment by sharkwouter** [comment]
Thanks! That's a pretty cool feature

**Pull request merged**
