### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by koraynilay**

### CODE REVIEW

**Comment by sharkwouter** [comment]
Thanks for the PR. It does look pretty good, but could you make it so only the Italian translation is included for now?

**Comment by koraynilay** [comment]
Sorry for the delay, is this ok?
Otherwise I'll re-fork and recreate the the PR.

**Comment by sharkwouter** [comment]
I've merged just the translation file with this commit: https://github.com/sharkwouter/minigalaxy/commit/0c3d4e4950d287ee92d6fa022e5467ba85faedd5

Thanks for contributing! Sorry for taking so long to figure this out.

**Comment by koraynilay** [comment]
Nice, thank you.

**Pull request closed without merging**
