### PR TITLE
Add progressbar download tooltip with percentage

### PR DESCRIPTION
**Pull request by TotalCaesar659**
This PR shows downloading percentage when hovering mouse over progressbar.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Good idea, but make sure you use ``GLib.idle_add`` for this, otherwise it will cause crashes.

**Comment by TotalCaesar659** [comment]
Got it.

**Comment by sharkwouter** [comment]
How do I use this? For me the tooltip does not seem to appear

**Comment by TotalCaesar659** [comment]
Try to hover mouse cursor over game picture first for showing game name and to progressbar after. This is weird  but works for me.

**Comment by sharkwouter** [comment]
Thanks!

**Pull request merged**
