### PR TITLE
Added Solus to the list of supported distributions.

### PR DESCRIPTION
**Pull request by Hawkeye0021**
Minigalaxy is now packaged for Solus and included in the official repositories.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Awesome! Could you add how to install it as well?

**Comment by Hawkeye0021** [comment]
Unfortunately I don't quite understand all the coding / syntax in that section of the read me to add it properly. The command would be `sudo eopkg it minigalaxy`

**Comment by sharkwouter** [comment]
No problem, I can add it. Thanks!

**Comment by sharkwouter** [comment]
I've added the instructions with commit 35d11b939e0b70aeb79040628ecc86e3eb1737d3. They are now shown on the README and on the website.

**Pull request merged**
