### PR TITLE
Update sv_SE.po

### PR DESCRIPTION
**Pull request by Newbytee**
Relates to https://github.com/sharkwouter/minigalaxy/issues/369

### CODE REVIEW

**Comment by Newbytee** [comment]
Side note: Whatever I do, it seems Minigalaxy displays in English, so I can't verify that the translations look good. I've tried setting LC_ALL, LANGUAGE, LANG; I've tried changing the in-app setting to something else; and I've tried settings my entire session to a different language. Regardless, Minigalaxy stays in English. Do you have any ideas?

**Comment by sharkwouter** [comment]
Did you run ``scripts/compile-translations.sh`` afterwards? Otherwise you might have set the language in the preferences to something other than system default. The translation looks good, though.

There are some issues with certain translations not being applied when not using LC_ALL at the moment and the properties dialog doesn't get translated for some reason, though.

**Comment by sharkwouter** [comment]
Thanks a lot, though, I've merged it.

**Comment by Newbytee** [comment]
> Did you run `scripts/compile-translations.sh` afterwards? Otherwise you might have set the language in the preferences to something other than system default. The translation looks good, though.
> 
> There are some issues with certain translations not being applied when not using LC_ALL at the moment and the properties dialog doesn't get translated for some reason, though.

Oh no, I didn't. I suppose that's why then. I recall you removed the output from the version control?

**Comment by sharkwouter** [comment]
Makes sense, I've checked it off

**Pull request merged**
