### PR TITLE
Added translation for Finnish

### PR DESCRIPTION
**Pull request by heidiwenger**
I hope all was done correct. This is my very first time using Github altogether.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Thanks for the MR. The translation looks pretty good and I'd love to merge this, but this is a little bit too big at the moment. Would it be possible to make another PR with only the file data/po/fi.po in it?

**Comment by heidiwenger** [comment]
> Thanks for the MR. The translation looks pretty good and I'd love to merge this, but this is a little bit too big at the moment. Would it be possible to make another PR with only the file data/po/fi.po in it?

How can i go about sending this one particular file..? Github and all this related i did, is totally new to me. Have been using Transifex and the likes before. I just followed those default instructions on how to commit. The checks now seem "All checks have passed" and "This branch has no conflicts with the base branch" though? I suppose i can't just drag and drop that .po file here right?

**Comment by sharkwouter** [comment]
I've merged this with #339

**Comment by sharkwouter** [comment]
Thanks for the translation. Sorry about taking forever to get to this.

**Pull request closed without merging**
